# this file is the config file for HongKong datasets.
labels:
  0 : "unlabeled"
  1 : "main_ground"
  2 : "tramway_road"
  3 : "high_vegetation"
  4 : "low_vegetation"
  5 : "building"
  6 : "poles"
  7 : "man-made objects"    # railings, fences, etc.
  8 : "cars"                # includes trucks, tramways, etc.
  9 : "pedestrians"         # includes cyclists

learning_map:
  0 : 0
  1 : 1
  2 : 1
  3 : 2
  4 : 3
  5 : 5
  6 : 4
  7 : 5
  8 : 5
  9 : 5

new_labels:
  0: "unlabeled"
  1: "ground"
  2: "high_vegetation"
  3: "low_vegetation"
  4: "poles"
  5: "man-made objects"   # includes buildings, cars, pedestrians, railing, etc.


#split: # sequence numbers
#  train:
#    - 1
#    - 2
#    - 3
#    - 4
#    - 5
#    - 6
#  val:
#    - 7
#  test:
#    - 7
split_all:
  - [0.9, 0.05, 0.05]